name: Nightly Playwright Dev Tests
on:
  pull_request:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
  issue_comment:

jobs:
  e2e-nightly-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: develop # TODO - this should come out of this config and env specific configs should provide it as input
    env: 
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        E2E_TEST_BASE_URL: ${{ vars.E2E_TEST_BASE_URL }}
        NODE_ENV: ${{ vars.NODE_ENV }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
    - name: Install Playwright Browsers
      working-directory: ./frontend
      run: pnpm exec playwright install --with-deps
    - name: Print environment variables (for debugging)
      run: |
        echo "E2E_TEST_BASE_URL is $E2E_TEST_BASE_URL"
        echo "SUPABASE_URL is $SUPABASE_URL"
    - name: Start Next.js app
      run: |
        pnpm run dev & # Start Next.js app in the background
        NEXTJS_PID=$!  # Capture the PID of the Next.js process
        echo "Started Next.js with PID $NEXTJS_PID"
        echo "NEXTJS_PID=$NEXTJS_PID" >> $GITHUB_ENV  # Store the PID for later use
        echo "Waiting for Next.js app to start..."
        until curl -s --head --request GET http://localhost:3000 | grep "200 OK"; do
          echo "Waiting for Next.js to be available..."
          sleep 5
        done
        echo "Next.js app is up and running!"
    - name: Run Playwright tests
      working-directory: ./frontend
      run: pnpm exec playwright test e2e
    - name: Upload Playwright JUnit XML Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: playwright-junit-report
        path: frontend/playwright-report/results.xml
    - name: Publish JUnit Test Results to GitHub Checks
      uses: actions/upload-test-results@v2
      with:
        test-results: frontend/playwright-report/results.xml  
    - name: Clean up
      run: |
        if [ -n "$NEXTJS_PID" ]; then
          kill $NEXTJS_PID
          echo "Killed Next.js process with PID $NEXTJS_PID"
        else
          echo "No Next.js process found."
        fi
